[package]
name = "safeboy"
version = "0.1.0"
authors = ["Alberto Fern√°ndez <albertofem@gmail.com>"]

[[bin]]
doc = false
name = "safeboy"
path = "src/safeboy.rs"

[dependencies]
clap = "*"
glium = "0.19.*"
blip_buf = ">=0.1.4"